# templates/networkpolicy.yaml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
spec:
  podSelector:
    {{- with .Values.selector }}
    matchLabels:
      {{- toYaml . | nindent 6 }}
    {{- end }}
  policyTypes:
    - Ingress
    - Egress
  {{- with .Values.ingress }}
  ingress:
    {{- toYaml . | nindent 2 }}
  {{- end }}
  {{- with .Values.egress }}
  egress:
    {{- toYaml . | nindent 2 }}
  {{- end }}